apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-servicey-monitor
  namespace: pedidos-env
  labels:
    release: observability
spec:
  selector:
    matchLabels:
      app: hexagonal-api
  namespaceSelector:
    matchNames:
      - pedidos-env
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
